### ISSUE TITLE
renaming this component

### ISSUE THREAD

**Issue by vnallamhawk** [Khan/react-multi-select#10]
Hello Team,

could you please rename this package to some acceptable name in industry standards. khan academy is not a name which someone in a company would be pleased with. Thanks.

**Comment by BrianGenisio** [comment]
@vnallamhawk I'm not following.  What does this mean? 

> khan academy is not a name which someone in a company would be pleased with.

Note that `@khanacademy` is the scope and the name of the component is `react-multi-select`.  

What would you suggest we change it to?

**Comment by vnallamhawk** [comment]
Hello Brian,

Can we remove the scope and just have it as react-multi-select. 

Having @khanacademy in the imports is definitely not something which a client would be happy with which infact will reduce this component from being used by  many people.

 import MultiSelect from '@khanacademy/react-multi-select'

**Comment by BrianGenisio** [comment]
@vnallamhawk I'm still not understanding why anyone would have a problem with the scope?  

The reason we use a scope is because `react-multi-select` is already taken in the NPM registry.  It is very common among NPM publishers to scope their packages for this reason.  When I search for `react-multi-select`, I find another company scoping their package (`@zooshgroup/react-native-multiple-select`) which uses scopes.  It is quite common. 

Can you explain to me why a client would care if a component has the scope name of the company who produced it?  It doesn't change anything about who produced it whether the scope exists or not.  For example, React is still produced by Facebook, even if they don't scope their packages in NPM.  Would people use it less if they needed to `import React from 'react';` vs `import React from '@facebook/react';`?  I worked as a consultant for many years, working with many clients, and I still don't understand.

In our case, either way, the license stays the same (MIT).  

Perhaps I'm missing something.  I'm not telling you that you are wrong... I just don't understand the problem with using scopes.  Can you point me to some best practices that suggests scoping is a problem?  I'd like to learn more.

**Comment by BrianGenisio** [comment]
Another thought... this license (MIT) lets you do pretty much anything you want with it.  There is nothing stopping you from forking it, re-naming it to `react-moolti-select` and publishing it to NPM to appease your client.  Would that be a solution?

**Comment by vnallamhawk** [comment]
Hello Brian,

I might be wrong. Thanks for your inputs.

**Comment by BrianGenisio** [comment]
Ok, I might be wrong too!  I'm going to close this, but if you'd like to discuss it further, I'm happy to re-open.
